### ISSUE TITLE
Ubuntu `before adsf install` instructions outdated on 20.04

### ISSUE THREAD

**Issue by SimunKaracic** [asdf-vm/asdf-erlang#149] opened 2020-06-07 10:42 UTC
The library `libwxgtk3.0-dev` was changed to `libgtk3.0-gtk3-dev` in 20.04, 
so the instructions need updating. I see there is already a PR for something similar, so let me know if You will fix this, or if You'd prefer it if I made a new one.

The exact error and solution is here: 
https://askubuntu.com/questions/1241217/package-libwxgtk3-0-dev-has-no-installation-candidate-on-ubuntu-20-04

**Comment by Stratus3D** [comment] 2020-06-09 14:52
@SimunKaracic I am working on improving that section of the readme. I just merged a change based on that open PR you saw and I think my changes address the change to the `libwxgtk3.0-dev` package. If you think what I have could be improved I'd welcome another PR! The readme is a bit messy and there is definitely room for improvement.

**Comment by Stratus3D** [comment] 2021-07-23 19:13
PR has been updated. I can confirm the updated readme is correct because I just installed Erlang with libwx on Ubuntu 20.04 this week.

**Closed by Stratus3D** 2021-07-23 19:13 UTC
