### ISSUE TITLE
Not able to list-all erlang : Failed to install kerl on ubuntu 20.04 fresh system

### ISSUE THREAD

**Issue by alpeshjamgade** [asdf-vm/asdf-erlang#218] opened 2021-09-20 04:28 UTC
$ asdf list-all erlang
>>>
Downloading kerl...
chmod: cannot access '/home/necron/.asdf/plugins/erlang/kerl': No such file or directory
Failed to install kerl

**Comment by Stratus3D** [comment] 2022-03-02 19:00
Hi @alpeshjamgade , sorry for the extremely late response. Have you tried this with the latest version of asdf-erlang? `asdf plugin-update erlang` should get you the latest version installed.

If that doesn't fix your issue can you paste the output of `asdf info` here so I can see more details on your OS environment? Thanks!

**Comment by Stratus3D** [comment] 2022-03-11 15:28
Closing due to lack of a response.

**Closed by Stratus3D** 2022-03-11 15:28 UTC

**Comment by iNath** [comment] 2022-04-30 06:33
In case someone goes through it, I had the same problem.

Caused by `curl` option -o which fails if the path contains hidden path (here: `~/.asdf`), see here: https://github.com/asdf-vm/asdf-erlang/blob/master/bin/utils.sh#L38
But only for `curl` version installed with`snap`... don't know why (see here: https://askubuntu.com/a/1372732)

So this fix the problem for me :
```
sudo snap remove curl
sudo apt install curl
```

**Comment by raywu** [comment] 2023-05-04 08:16
Thanks @iNath - my problem was that `curl` was not set up at all on my machine. Your suggestion worked!

```
sudo apt install curl
```

**Comment by vinodgadade** [comment] 2023-12-07 10:55
Thanks @iNath

**Comment by vinodgadade** [comment] 2023-12-07 10:57
> In case someone goes through it, I had the same problem.
> 
> Caused by `curl` option -o which fails if the path contains hidden directory (here: `~/.asdf`), see here: https://github.com/asdf-vm/asdf-erlang/blob/master/bin/utils.sh#L38 But only for `curl` version installed with`snap`... don't know why (see here: https://askubuntu.com/a/1372732)
> 
> So this fix the problem for me :
> 
> ```
> sudo snap remove curl
> sudo apt install curl
> ```

Thanks @iNath
