### ISSUE TITLE
Build failed on MacOS

### ISSUE THREAD

**Issue by Bittree** [asdf-vm/asdf-erlang#137] opened 2020-04-28 10:03 UTC
errors throw out with the command
```
asdf install erlang latest:21
```
and Build failed with error throw out:
```
Build failed.
gmake[4]: *** [x86_64-apple-darwin19.4.0/Makefile:802: /Users/guoyutao/.asdf/plugins/erlang/kerl-home/builds/asdf_21.3.8.15/otp_src_21.3.8.15/bin/x86_64-apple-darwin19.4.0/erl_child_setup] Error 1
gmake[4]: *** Waiting for unfinished jobs....
gmake[4]: Leaving directory '/Users/guoyutao/.asdf/plugins/erlang/kerl-home/builds/asdf_21.3.8.15/otp_src_21.3.8.15/erts/emulator'
gmake[3]: *** [/Users/guoyutao/.asdf/plugins/erlang/kerl-home/builds/asdf_21.3.8.15/otp_src_21.3.8.15/make/run_make.mk:35: opt] Error 2
gmake[3]: Leaving directory '/Users/guoyutao/.asdf/plugins/erlang/kerl-home/builds/asdf_21.3.8.15/otp_src_21.3.8.15/erts/emulator'
gmake[2]: *** [Makefile:45: opt] Error 2
gmake[2]: Leaving directory '/Users/guoyutao/.asdf/plugins/erlang/kerl-home/builds/asdf_21.3.8.15/otp_src_21.3.8.15/erts'
gmake[1]: *** [Makefile:54: smp] Error 2
gmake[1]: Leaving directory '/Users/guoyutao/.asdf/plugins/erlang/kerl-home/builds/asdf_21.3.8.15/otp_src_21.3.8.15/erts'
gmake: *** [Makefile:474: emulator_profile_generate] Error 2
```
and got errors below in build log:
```
gmake[6]: Leaving directory '~/.asdf/plugins/erlang/kerl-home/builds~/.asdf_21.3.8.15/otp_src_21.3.8.15/erts/lib_src'
gmake[5]: Leaving directory '~/.asdf/plugins/erlang/kerl-home/builds~/.asdf_21.3.8.15/otp_src_21.3.8.15/erts/lib_src'
 LD     ~/.asdf/plugins/erlang/kerl-home/builds~/.asdf_21.3.8.15/otp_src_21.3.8.15/bin/x86_64-apple-darwin19.4.0/erl_child_setup
ld: weak import of symbol '___darwin_check_fd_set_overflow' not supported because of option: -no_weak_imports for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
gmake[4]: *** [x86_64-apple-darwin19.4.0/Makefile:802: ~/.asdf/plugins/erlang/kerl-home/builds~/.asdf_21.3.8.15/otp_src_21.3.8.15/bin/x86_64-apple-darwin19.4.0/erl_child_setup] Error 1
gmake[4]: *** Waiting for unfinished jobs....
gmake[4]: Leaving directory '~/.asdf/plugins/erlang/kerl-home/builds~/.asdf_21.3.8.15/otp_src_21.3.8.15/erts/emulator'
gmake[3]: *** [~/.asdf/plugins/erlang/kerl-home/builds~/.asdf_21.3.8.15/otp_src_21.3.8.15/make/run_make.mk:35: opt] Error 2
gmake[3]: Leaving directory '~/.asdf/plugins/erlang/kerl-home/builds~/.asdf_21.3.8.15/otp_src_21.3.8.15/erts/emulator'
gmake[2]: *** [Makefile:45: opt] Error 2
gmake[2]: Leaving directory '~/.asdf/plugins/erlang/kerl-home/builds~/.asdf_21.3.8.15/otp_src_21.3.8.15/erts'
gmake[1]: *** [Makefile:54: smp] Error 2
gmake[1]: Leaving directory '~/.asdf/plugins/erlang/kerl-home/builds~/.asdf_21.3.8.15/otp_src_21.3.8.15/erts'
gmake: *** [Makefile:474: emulator_profile_generate] Error 2
```

But when i try the same command on Ubuntu it`s installed well.So maybe there are some issues with MacOS?

MacOS Version:
```
ProductName:	Mac OS X
ProductVersion:	10.15.4
BuildVersion:	19E287
Kernel Version 19.4.0
```

**Comment by Stratus3D** [comment] 2020-04-28 12:59
I believe this is a duplicate of https://github.com/asdf-vm/asdf-erlang/issues/116

**Closed by Stratus3D** 2020-04-28 12:59 UTC
